version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ajay
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: hackathon6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
 postgres_data: